/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mensajeterminos;

import mensajeterminos.recursos.Archivo;
//import ElementosVisuales.dialogoMensaje;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Wilver
 */
public class panelTC extends javax.swing.JPanel {

    private dialogoMensaje terminos;
    private String textoTerminos="Mis terminos y mis condiciones";
    private String titulo;
    private boolean estado = false; //me ayuda a saber si la casilla es seleccionada
    /**
     * Creates new form panelTC
     */
    public panelTC() {
        initComponents();
        titulo = lblTerminos.getText();
        terminos = new dialogoMensaje(null, true, textoTerminos);
    }
    
    //constructor sobre cargado que permite personalisar el mensaje de los terminos y condiciones al enviar un String
    public panelTC(String titulo, String textoTerminos) {
        initComponents();
        this.titulo = titulo;
        lblTerminos.setText(titulo);
        terminos = new dialogoMensaje(null, true, textoTerminos);
    }
    
    public boolean getBandera() { return estado; }
    public String getTextoTerminos(){ return textoTerminos;}
    public String getTitulo(){return titulo;}
    
    public JButton getBoton(){ return btnAceptarTerminos1;}
    
    public void setTitulo(String titulo){ this.titulo = titulo; lblTerminos.setText(titulo);}
    public void setTextoTerminos(String texto){textoTerminos=texto; terminos.setTextoMensaje(texto);}
    public void setArchivo(String ruta){
        String nuevoTexto =  Archivo.leerArchivo(ruta);
        textoTerminos = nuevoTexto;
        terminos.setTextoMensaje(nuevoTexto);
    }
    
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ckbTerminos = new javax.swing.JCheckBox();
        lblTerminos = new javax.swing.JLabel();
        btnAceptarTerminos1 = new mensajeterminos.BtnAceptar();

        ckbTerminos.setText("HE LEIDO Y ACEPTO");
        ckbTerminos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbTerminosActionPerformed(evt);
            }
        });

        lblTerminos.setForeground(new java.awt.Color(0, 0, 204));
        lblTerminos.setText("LOS TERMINOS Y CONDICIONES");
        lblTerminos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTerminosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTerminosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTerminosMouseExited(evt);
            }
        });

        btnAceptarTerminos1.setEnabled(false);
        btnAceptarTerminos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarTerminos1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ckbTerminos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTerminos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(btnAceptarTerminos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbTerminos)
                    .addComponent(lblTerminos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptarTerminos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ckbTerminosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbTerminosActionPerformed
        // TODO add your handling code here:
        if (ckbTerminos.isSelected()){ 
            btnAceptarTerminos1.setEnabled(true);        //Habilitar el boton solo si se marca la casilla
        } else {
            btnAceptarTerminos1.setEnabled(false);       //Desabilita el boton si la casilla no es marcada
        }
    }//GEN-LAST:event_ckbTerminosActionPerformed

    private void lblTerminosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTerminosMouseClicked
        // TODO add your handling code here:
        terminos.setVisible(true); //muestra el dialogo con los terminos y condiciones
    }//GEN-LAST:event_lblTerminosMouseClicked

    private void lblTerminosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTerminosMouseEntered
        // TODO add your handling code here:
        lblTerminos.setBackground(Color.gray);
        lblTerminos.setCursor(new Cursor(12));
    }//GEN-LAST:event_lblTerminosMouseEntered

    private void lblTerminosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTerminosMouseExited
        // TODO add your handling code here:
        lblTerminos.setBackground(this.getBackground());
        lblTerminos.setCursor(this.getCursor());
    }//GEN-LAST:event_lblTerminosMouseExited
    

    private void btnAceptarTerminos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarTerminosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Registrado existosamente", "Registro", 1);
        estado=true;
    }//GEN-LAST:event_btnAceptarTerminosActionPerformed
    // TODO add your handling code here:




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mensajeterminos.BtnAceptar btnAceptarTerminos1;
    private javax.swing.JCheckBox ckbTerminos;
    private javax.swing.JLabel lblTerminos;
    // End of variables declaration//GEN-END:variables
}
